# Generated by Django 5.1.5 on 2025-01-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='displayTheme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourites',
            field=models.BooleanField(default=True),
        ),
    ]
