# Generated by Django 5.1.5 on 2025-02-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_displaytheme_alter_profile_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='guestMode',
            field=models.BooleanField(default=False),
        ),
    ]
